[package]
name = "idm-clone"
version = "0.1.0"
edition = "2021"


[dependencies]
crossterm = "0.27.0"
fakeit = "1.2.0"
itertools = "0.13.0"
ratatui = { version = "0.26.3", features = ["crossterm"] }
unicode-width = "0.1.13"
